### ISSUE TITLE
Win Setup Release

### ISSUE THREAD

**Issue by raddacle** [Pong420/google-tasks-desktop#16]
Mainly just wanted to say how much I appreciate this client! With google killing every other official/non-official way of accessing tasks without going to gmail or calendar, this is much appreciated! Thank you.

Small issue though: the link for the Setup exe is not complete. I was able to access it by editing the url for the non-setup release.

**Comment by Pong420** [comment]
Thanks! 
The project is not stable enough.  I hope it will not cause trouble for you.

Sorry, I do not understand your issue. I cannot control/edit url

**Comment by raddacle** [comment]
Seems perfectly stable! Definitely snappier if it's installed rather than run off the portable version. 

The minor issue I was mentioning was that the Setup release doesn't have a full link. I don't whether you can control that, it's not a big deal otherwise.

**Comment by Pong420** [comment]
So your issue is you cannot install through "Steup.exe" ?

**Comment by raddacle** [comment]
Nevermind, sorry. This was a bug caused by the chrome extension "Clickable Links". I'll close this issue. Thanks again for your work towards this project!
