### ISSUE TITLE
Can't change list from edit menu

### ISSUE THREAD

**Issue by raddacle** [Pong420/google-tasks-desktop#23]
I'm on build 1.3.2 on Windows 10 x64, and I can't change list for an already created task from it's edit screen. When I click on the list drop down, nothing happens at all.

**Comment by Pong420** [comment]
Do you mean this dropdown? 
if yes it's correct, I do not handle this function. Maybe it will be included in the next release
<img width="412" alt="Screenshot 2019-06-24 at 11 50 45 AM" src="https://user-images.githubusercontent.com/19869384/59990617-5ea9bb80-9676-11e9-91f2-5ff9db9e6340.png">

**Comment by Pong420** [comment]
Please check out [1.4.0 Release](https://github.com/Pong420/google-tasks-desktop/releases/tag/1.4.0)
