### ISSUE TITLE
JavaScript error on load of of 2.0.1

### ISSUE THREAD

**Issue by t3hero** [Pong420/google-tasks-desktop#28]
Does not appear to happen on launch of any other versions. 

Running Win 10, attempting to run from Google.Tasks-2.0.1-win.zip

![Google_Tasks_vrJ8bv1I9L](https://user-images.githubusercontent.com/804380/63067209-54c96980-befd-11e9-9701-f4f3aded815e.png)

**Comment by Pong420** [comment]
Thanks for your report, please checkout [2.0.2](https://github.com/Pong420/google-tasks-desktop/releases/tag/2.0.2)
