### ISSUE TITLE
Stumbled across this project

### ISSUE THREAD

**Issue by ZYinMD** [Pong420/google-tasks-desktop#32]
Hi, I found this project by chance when searching "google tasks" on github. Great work!

I don't know if you're building this for yourself to use, but just want to mention that there's a chrome extension called "full screen for google tasks". Not sure if it fits your personal needs, if yes then it may help. (But probably not, because you didn't try to make your app wider than the gmail sidebar, so I guess the sidebar being too narrow wasn't the problem you wanted to fix)

**Comment by Pong420** [comment]
Thanks for your suggestion.  Actually, I do not use it many after created it.
I like to create some side projects for practice.
And I think It is inconvenient to check todo tasks by opening Gmail each time. 
So I create this project for myself and as a practice.
