### ISSUE TITLE
How i can change google secret Json file ?

### ISSUE THREAD

**Issue by letieu** [Pong420/google-tasks-desktop#40]
I have drag Json file, Then come to screen get Code, but I had drag a negative file, so i can't get code to comfirm. Now, when open app, it will auto show screen get code

**Comment by Pong420** [comment]
Open dev tools by shortcut / menu, then type `window.STORAGE_DIRECTORY` on the console. Open the directory return from console and delete the json files.
![Screen Shot 2020-07-23 at 4 42 58 PM](https://user-images.githubusercontent.com/19869384/88267987-40dcd900-cd04-11ea-8370-a4ed69289072.png)

**Comment by letieu** [comment]
> 1. Open dev tools by shortcut / menu, then type `window.STORAGE_DIRECTORY` on the console.

![image](https://user-images.githubusercontent.com/53562817/88362417-a5e90b00-cda6-11ea-9cd2-3fb77fd7e300.png)
It like this, i don't know how open dev tools ?

**Comment by Pong420** [comment]
Sorry, I am not sure. please try 

1. Shortcut `ctrl+shift+i`

2. menu at the top of computer screen
![Screen Shot 2020-07-24 at 1 15 54 PM](https://user-images.githubusercontent.com/19869384/88362678-0466b700-cdb0-11ea-8abc-9bee0968a59a.png)

3. Right click the top of application
![88362417-a5e90b00-cda6-11ea-9cd2-3fb77fd7e300](https://user-images.githubusercontent.com/19869384/88362689-0b8dc500-cdb0-11ea-8761-89bde21427a0.png)

**Comment by letieu** [comment]
> Sorry, I am not sure. please try

Thank for your support, I fix it by find key word "google-task-desktop" end delete Othen2.json file , your app is so useful, Thank you :)
