### ISSUE TITLE
API access guide outdated/incomplete/broken?

### ISSUE THREAD

**Issue by MarcinOrlowski** [Pong420/google-tasks-desktop#42]
Hi, I got a feeling that the setup procedure (for API access) described in README is either outdated or not suitable for freshly set google accounts. Could you please confirm this is not the case as I simply stuck seeing not steps to execute as you described.

**Comment by Pong420** [comment]
Maybe you could refer to below document
https://support.google.com/cloud/answer/6158849?hl=en

Except step 6, you should select `Desktop app` as the application type.

After OAuth client created, you could download the `OAuth .json` by clicking this button
<img width="823" alt="Screen Shot 2020-08-05 at 10 14 14 PM" src="https://user-images.githubusercontent.com/19869384/89423455-190c5d00-d769-11ea-90e4-e67d6b9ac90a.png">

I will update the readme after you have succeeded

**Comment by sciencyboi** [comment]
> I will update the readme after you have succeeded

It works

**Comment by MarcinOrlowski** [comment]
This is not my case unfortunatelly. To be able to create Credentials it tells me to create consent screen.

![g1](https://user-images.githubusercontent.com/8041294/91842784-ed3fa280-ec54-11ea-906b-f96f77741ca6.png)

But that's pretty unclear for me what is that for and since it also tells me that I only can set user type to be "any user with google account". Since I do not really know what are the implications and what I am doing here, I'd appreciate some assistance.

![g2](https://user-images.githubusercontent.com/8041294/91842896-1fe99b00-ec55-11ea-90f5-1b0bfbd5349a.png)

**Comment by Pong420** [comment]
Maybe you could take a look at the [document](https://support.google.com/cloud/answer/6158849). It may better than my explanation since I am not good at English.
It explains the user consent and difference between `internal` and `external` (in Public and internal applications)

**Comment by MarcinOrlowski** [comment]
Thanks. For a record. I selected "External" and just filled the name and saved consent screen. Then I went back to Credentials and went from there. The "Get code" step triggered warning "This app isn't verified" but I clicked "Advanced" and then "Go to ... (unsafe)", granted the permissions, copied the code and pasted to the app,  and that seems to be it.
