### ISSUE TITLE
Main screen typo

### ISSUE THREAD

**Issue by MarcinOrlowski** [Pong420/google-tasks-desktop#43]
It should read "client" not "clinet": 

https://github.com/Pong420/google-tasks-desktop/blob/bf94c82e164e5fe1492812b63ea26f0ecd515654/src/pages/Auth/Auth.tsx#L23

It is also visible on main screenshots.
<img width="327" alt="1" src="https://user-images.githubusercontent.com/8041294/89421258-16dbdb80-d734-11ea-86ba-9446c57f1604.png">

**Comment by Pong420** [comment]
Thanks,
Since it is not much important, it will fix until the next essential update.
I will leave the issue open until fixed version released.

**Comment by Pong420** [comment]
fixed in `3.1.0`
