### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by phaalonso** [Pong420/google-tasks-desktop#44]
Hi, I am trying to use the app, but after dragging the JSON file it only shows a white screen
![image](https://user-images.githubusercontent.com/26033899/91096933-35e3d400-e635-11ea-9bf4-e8c8c9967f5a.png)

**Comment by Pong420** [comment]
What is your OS ? 
Try `ctrl+shift+i` to open the dev menu and see is there any error?
<img width="971" alt="Screen Shot 2020-08-25 at 8 26 49 AM" src="https://user-images.githubusercontent.com/19869384/91109171-bb569b00-e6ac-11ea-95e4-c79a1d24fffd.png">

**Comment by phaalonso** [comment]
I'm using Ubuntu 20.04, tring to open the Dev Tools don't did anything. It only stays in that white screen

**Comment by phaalonso** [comment]
I tried to run the dev and found the error. 
 - How I can reset the oauth2 file? 
 - I think that it needs to catch the error and show a screen saying to the user reupload the file with the error that occurred.

![image](https://user-images.githubusercontent.com/26033899/91168953-dde8b400-e6ac-11ea-8996-c656347aea79.png)

**Comment by Pong420** [comment]
> How I can reset the oauth2 file?

See #40. What is your content of your oauth2.json?
If you are upload successful and `v3.0.2` should allow to go back and use another outh2.json. 

<img width="412" alt="Screen Shot 2020-08-25 at 7 55 42 PM" src="https://user-images.githubusercontent.com/19869384/91172131-41ef9480-e70e-11ea-80fa-23421082073d.png">


> I think that it needs to catch the error and show a screen saying to the user reupload the file with the error that occurred.

This error should not appear in production and not related to your issue.
Most probably because `.ts` file in electron folder are not compile correctly. Please try run `yarn electron:compile` before `yarn dev`.

**Comment by phaalonso** [comment]
I am using `v3.0.2` downloaded from the releases page. Trying both AppImage and .deb file. The only thing that shows after I put the json file is a white screen and nothing works, it doesn't even open the dev tools.

Running `yarn electron:compile` and `yarn dev` gives the same error.

**Comment by Pong420** [comment]
Could you remove the secret content of oauth2.json and post it here ? 
I have not any Linux OS and cannot reproduce.

**Comment by phaalonso** [comment]
You are using the `yarn dev` or `yarn app:dev` for development? 

Here in both of them `oAuth2Storage` and `tokenStorage` don't exist. There seem to be some problem with window object

Some small changes in `services/auth.ts`:
```ts
const { oAuth2Storage, tokenStorage } = window;

export let OAuth2Keys = oAuth2Storage ? oAuth2Storage.get() : undefined;
```
```ts
export function authenticate() {
  const token = tokenStorage ? tokenStorage.get() : undefined;
  if (oAuth2Client && token) {
```

Only made the error occurred in when trying to access the `window` in another file 
![image](https://user-images.githubusercontent.com/26033899/91188586-d84c9780-e6c7-11ea-98b4-2e146020a3bc.png)

**Comment by phaalonso** [comment]
> Could you remove the secret content of oauth2.json and post it here ?
> I have not any Linux OS and cannot reproduce.

Sure, here is it:
```json
{
	"installed":{
		"client_id": "...",
		"project_id": "...",
		"auth_uri":"https://accounts.google.com/o/oauth2/auth",
		"token_uri":"https://oauth2.googleapis.com/token",
		"auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
		"client_secret": "...",
		"redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]
	}
}
```

**Comment by Pong420** [comment]
> You are using the `yarn dev` or `yarn app:dev` for development?
`yarn dev` will run the `cmd` in `./Procfile`
```
react: npm run app:dev
electron: node scripts/electron-wait-react.js
```
`app:dev` start a local server and `scripts/electron-wait-react.js` monitor the dev server.
After server is ready, electron will be start and open `http://localhot:3000`
The objects in `window` are handled in `electron/preload/index.ts`

**Comment by Pong420** [comment]
I have install Ubuntu on VirtualBox. And download and install the `google-tasks-desktop_3.0.2_amd64.deb` in release page. Then I just create an `oauth2.json` file and paste the content you posted. 
It is work for me. 
![Screen Shot 2020-08-25 at 11 20 10 PM](https://user-images.githubusercontent.com/19869384/91193320-89374e80-e729-11ea-8fd8-f5d85c0d9784.png)

I will try other method on tomorrow

**Comment by Pong420** [comment]
You may delete the oauth2.json and try again
![Screen Shot 2020-08-25 at 11 34 57 PM](https://user-images.githubusercontent.com/19869384/91195541-ae2cc100-e72b-11ea-9776-fcac88597bf6.png)

**Comment by phaalonso** [comment]
Thanks! It works now
