### ISSUE TITLE
Icon for the appimage not being dislayed in taskbar

### ISSUE THREAD

**Issue by sciencyboi** [Pong420/google-tasks-desktop#45]
Hi!
First of all, thanks for the app!

Second, the .desktop file created by appimage integration has the wrong WMC Class, due to which the icon of the app isn't displayed at all in the taskbar/dock.
appimage source : [https://www.linux-apps.com/p/1308711/](https://www.linux-apps.com/p/1308711/)
It is : `StartupWMClass=Google Tasks`
and should be : `StartupWMClass=google-task-desktop` instead.

The issue is minor one and can be fixed easily. :)

**Comment by Pong420** [comment]
Hi, your appimage source seems to be outdated. 
Please download and try version [v3.0.2](https://github.com/Pong420/google-tasks-desktop/releases/tag/3.0.2). If not working you may also try the [v3.0.3-rc.1](https://github.com/Pong420/google-tasks-desktop/releases/tag/3.0.3-rc.1).

**Comment by sciencyboi** [comment]
yeah it works in the later version. Thanks!

**Comment by Pong420** [comment]
The latest version means `v3.0.2` or `v3.0.3-rc.1`? 
Since i have try to add `StartupWMClass` on `v3.0.3-rc.1`

**Comment by sciencyboi** [comment]
It works on v3.0.3-rc.1
