### ISSUE TITLE
Have close/maximize/minimize buttons matching the OS/desktop environment in use.

### ISSUE THREAD

**Issue by pedrofleck** [Pong420/google-tasks-desktop#48]
Currently, the app uses macOS buttons that make it look very odd on Linux. It doesn't even have to match every DE out there, just a regular X close button on the right would be fine.
Example:
![Captura de tela de 2020-09-11 16-34-56](https://user-images.githubusercontent.com/761321/92966010-22b27000-f44d-11ea-9dd8-a43136c36791.png)

**Comment by Pong420** [comment]
I will try to add an option to switch the style but not sure the time

**Comment by pranavAbe** [comment]
UI has been fixed in release 3.1.0-rc.1

**Comment by Pong420** [comment]
The title bar in `3.1.0-rc.1` is not stable.

**Comment by Pong420** [comment]
Hi, please try [3.1.0-rc.2](https://github.com/Pong420/google-tasks-desktop/releases/tag/3.1.0-rc.2).

**Comment by pedrofleck** [comment]
Sorry it took me so long to comment, but it is looking great! My only complaint would be that in the "Preferences" view, the "Close task" button looks a bit out of place, perhaps it could go to the same line as the title.
![Captura de tela de 2020-11-21 15-36-17](https://user-images.githubusercontent.com/761321/99884784-8dcbb000-2c0f-11eb-9075-e0c7256f6310.png)

**Comment by Pong420** [comment]
please try `3.1.0-rc.3`

**Comment by pedrofleck** [comment]
Now it is perfect, thanks a lot!
