### ISSUE TITLE
All tasks not syncing to desktop client

### ISSUE THREAD

**Issue by pranavAbe** [Pong420/google-tasks-desktop#51]
Only 11 tasks (out of 24 tasks that I have on Google Tasks) show up on the desktop client. The number of completed tasks is also not synced correctly; the desktop client shows 9 completed tasks whereas I have 211 completed tasks.

**Comment by Pong420** [comment]
Hi, which version are you using?

**Comment by Pong420** [comment]
I found the root cause. 
`google-tasks-API` limited the number of tasks return ( defaults to 20 ).
I think to create an option to control the number of tasks return ( max 100 ) is enough.
Or any suggestion on the trigger point of `load more` task?

**Comment by pranavAbe** [comment]
Does the `load more` trigger point value only involve the number of *active* tasks? As in, if I have 110 *active* tasks and the trigger point is 100 tasks, do I get the `load more` after a 100 tasks? Or does that count of hundred involve the loading up of *completed* tasks also?

**Comment by Pong420** [comment]
Maybe just continue query until no more tasks (active & completed) or archive the limited ( configure in preferences )

**Comment by pranavAbe** [comment]
Sounds good to me. Looking forward to the update.

**Comment by Pong420** [comment]
Please try [3.1.0-rc.1](https://github.com/Pong420/google-tasks-desktop/releases/tag/3.1.0-rc.1).

**Comment by pranavAbe** [comment]
It works fine now. Thanks for the prompt update.
