### ISSUE TITLE
⚠️ Failed to register Appimage in system via libappimage

### ISSUE THREAD

**Issue by TheDudeThatCode** [Pong420/google-tasks-desktop#66]
- Whenever I try to integrate this, I get an error. I guess some module updates are required.
- @Pong420 please have a look at this :bow: 

![image](https://user-images.githubusercontent.com/41606999/125426097-7fa06b36-c94a-4412-adf1-a6b5df2b32d1.png)

**Comment by Pong420** [comment]
Sorry, my linux is down. I cannot test the appi image.
You could clone the project and build yourself
```
yarn install
yarn package
```

**Comment by TheDudeThatCode** [comment]
@Pong420 sure will check it out and let you know :)

**Comment by Pong420** [comment]
As mention in https://github.com/Pong420/google-tasks-desktop/issues/67#issuecomment-889135865
The issue should be fixed in [3.1.3](https://github.com/Pong420/google-tasks-desktop/releases)

**Comment by TheDudeThatCode** [comment]
@Pong420 yes this is fixed now, and everything is working fine :+1: , you can close this issue now thank you  :pray: 

![image](https://user-images.githubusercontent.com/41606999/127505530-79d4d7d6-c0cf-42bf-8509-76abdca3841a.png)
