### ISSUE TITLE
wrong icon name on DEB

### ISSUE THREAD

**Issue by varlesh** [Pong420/google-tasks-desktop#67]
```
[Desktop Entry]
Name=Google Tasks
Exec="/opt/Google Tasks/google-tasks-desktop" %U
Terminal=false
Type=Application
Icon=./public/icon/icon.png
StartupWMClass=google-tasks-desktop
Encoding=UTF-8
Comment=Unofficial google tasks desktop application
Categories=Utility;
```
icon installed on hicolor theme directory need change to:
`Icon=google-tasks-desktop`

https://github.com/Pong420/google-tasks-desktop/blob/master/package.json#L93

**Comment by Pong420** [comment]
Thanks, are you confirm this change fixes the issue?
If not, could you try the new release of [3.1.2-deb](https://github.com/Pong420/google-tasks-desktop/releases/tag/3.1.2-deb) works fine? Or clone the repo and pack it yourself

**Comment by varlesh** [comment]
Yes, thx :+1:

**Comment by varlesh** [comment]
This line needed?
https://github.com/Pong420/google-tasks-desktop/blob/master/package.json#L87

**Comment by varlesh** [comment]
maybe it's broken appimage too...

**Comment by varlesh** [comment]
I think it's related with #66 issue:
```
./Google.Tasks-3.1.2_d480d7caef5a55da2e06acc473bb41c1.AppImage
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 615, resource id: 16066855, major code: 40 (TranslateCoords), minor code: 0
ERROR: appimage_register_in_system : Icon field contains path
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 779, resource id: 16066939, major code: 40 (TranslateCoords), minor code: 0

```

**Comment by Pong420** [comment]
I check out the [documentation](https://www.electron.build/configuration/linux) again, its value is incorrect. I have uploaded a fixed version. Could you test for it?

https://github.com/Pong420/google-tasks-desktop/releases/tag/3.1.3

**Comment by varlesh** [comment]
All fine, you can close #66

**Comment by Pong420** [comment]
thanks !
